# Set to an integer for a specific number of cores to use or "auto" to let the processes use all
# the available cores.
multiprocess: auto

# Name of the dataset to download from HuggingFace.
dataset_name: Babelscape/multinerd

# Path to the model checkpoint. Either on Huggingface or on disk.
model_checkpoint: distilbert-base-multilingual-cased

# Training Arguments for Trainer. You can choose to add or remove any arguments.
training_arguments: {
  output_dir: models/multinerd/distilbert-base-multilingual-cased,
  learning_rate: 5.0e-5,
  weight_decay: 0.01,
  num_train_epochs: 1,
  per_device_train_batch_size: 32,
  per_device_eval_batch_size: 32,
  gradient_accumulation_steps: 4,
  load_best_model_at_end: True,
  fp16: True,
  report_to: None,
  evaluation_strategy: epoch,
  save_strategy: epoch,
  logging_strategy: steps,
}

# Wandb logging configs. Don't forget to set your WANDB_API_KEY and WANDB_ENTITY in wandb_env_var.yaml
wandb_project_name: nre
wandb_env_var_path: wandb_env_var.yaml

# Configurations for System A.
systemA: {
  # Path to save/load System A dataset to/from disk.
  dataset_path: processed_dataset/multinerd/SystemA,

  # Configurations for dataset loading/processing.
  load_ds_from_disk: False,
  preprocess: True,

  # System A Label to ID dictionary.
  label2id: {
    "O": 0,
    "B-PER": 1,
    "I-PER": 2,
    "B-ORG": 3,
    "I-ORG": 4,
    "B-LOC": 5,
    "I-LOC": 6,
    "B-ANIM": 7,
    "I-ANIM": 8,
    "B-BIO": 9,
    "I-BIO": 10,
    "B-CEL": 11,
    "I-CEL": 12,
    "B-DIS": 13,
    "I-DIS": 14,
    "B-EVE": 15,
    "I-EVE": 16,
    "B-FOOD": 17,
    "I-FOOD": 18,
    "B-INST": 19,
    "I-INST": 20,
    "B-MEDIA": 21,
    "I-MEDIA": 22,
    "B-MYTH": 23,
    "I-MYTH": 24,
    "B-PLANT": 25,
    "I-PLANT": 26,
    "B-TIME": 27,
    "I-TIME": 28,
    "B-VEHI": 29,
    "I-VEHI": 30,
  }
}

# Configurations for System B.
systemB: {
  # Path to save/load System B dataset to/from disk.
  dataset_path: processed_dataset/multinerd/SystemB,

  # Configurations for dataset loading/processing.
  load_ds_from_disk: False,
  preprocess: True,

  # Removed entity tags of MultiNERD.
  removed_tags: [ 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 ],

  # Changed entity tags of MultiNERD.
  changed_tags: {
    13: 9,
    14: 10,
  },

  # System B Label to ID dictionary.
  label2id: {
    "O": 0,
    "B-PER": 1,
    "I-PER": 2,
    "B-ORG": 3,
    "I-ORG": 4,
    "B-LOC": 5,
    "I-LOC": 6,
    "B-ANIM": 7,
    "I-ANIM": 8,
    "B-DIS": 9,
    "I-DIS": 10,
  }
}